apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app-deployment
  labels:
    app: contact-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-app
  template:
    metadata:
      labels:
        app: contact-app
    spec:
      containers:
        - name: contact-app
          image: hela18/contact-app:latest
          ports:
            - containerPort: 8080
